// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP_3nrjsCaFFzQ_M9G5nargTUNytMIlDY',
    appId: '1:150227549504:web:cd2d3afd5f31ee6b5b4ea5',
    messagingSenderId: '150227549504',
    projectId: 'movini-dc6c4',
    authDomain: 'movini-dc6c4.firebaseapp.com',
    storageBucket: 'movini-dc6c4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkXOBx5lsb45lGbE24T5LxmVWy3JL9x_I',
    appId: '1:150227549504:android:34c61fece44dc06b5b4ea5',
    messagingSenderId: '150227549504',
    projectId: 'movini-dc6c4',
    storageBucket: 'movini-dc6c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbEcIlHYwOHpSiP7tl7nZUCE-UIG_Bk78',
    appId: '1:150227549504:ios:8243045f11275ef75b4ea5',
    messagingSenderId: '150227549504',
    projectId: 'movini-dc6c4',
    storageBucket: 'movini-dc6c4.firebasestorage.app',
    iosBundleId: 'com.example.movini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbEcIlHYwOHpSiP7tl7nZUCE-UIG_Bk78',
    appId: '1:150227549504:ios:8243045f11275ef75b4ea5',
    messagingSenderId: '150227549504',
    projectId: 'movini-dc6c4',
    storageBucket: 'movini-dc6c4.firebasestorage.app',
    iosBundleId: 'com.example.movini',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP_3nrjsCaFFzQ_M9G5nargTUNytMIlDY',
    appId: '1:150227549504:web:54794327216dbe025b4ea5',
    messagingSenderId: '150227549504',
    projectId: 'movini-dc6c4',
    authDomain: 'movini-dc6c4.firebaseapp.com',
    storageBucket: 'movini-dc6c4.firebasestorage.app',
  );
}
